events {}

http {

    access_log /logs/access.log;
    error_log /logs/error.log;

    server {
        listen 80;

        ssi on;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /hostname {
            return 200 "$hostname";
        }
    }
}