services:

  web1:
    image: webserver1
    container_name: web1
    volumes:
      - ./logs/web1:/logs
      - ./html:/usr/share/nginx/html

  web2:
    image: webserver2
    container_name: web2
    volumes:
      - ./logs/web2:/logs
      - ./html:/usr/share/nginx/html

  loadbalancer:
    image: loadbalancer
    container_name: loadbalancer
    ports:
      - "8080:80"
    depends_on:
      - web1
      - web2